[package]
name = "partition_ga"
version = "0.1.0"
authors = ["Henshaw, Andy <Andy.Henshaw@gtri.gatech.edu>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
mysql = "*"
rand = "0.5.2"
itertools = "0.8.2"
